version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    container_name: monitoring-grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    user: 1000:1000
    hostname: rpi-grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  node-exporter:
    container_name: monitoring-node-exporter
#    ports:
#      - 9100:9100
#    expose:
#      - 9100
    hostname: rpi-exporter
#    network_mode: host
    image: prom/node-exporter:latest
    restart: unless-stopped

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    container_name: monitoring-prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    hostname: rpi-prom
    image: prom/prometheus:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    links:
      - node-exporter:node-exporter

  blackbox_exporter:
    image: prom/blackbox-exporter:master
    container_name: blackbox_exporter
    restart: unless-stopped
    #    extra_hosts: *pi
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox_config.yml:/etc/blackbox_exporter/config.yml

#  rpi_cpu_stats:
#    image: thundermagic/rpi_cpu_stats:latest
#    container_name: rpi_cpu_stats
#    restart: unless-stopped
#    ports:
#      - "9669:9669"
#    environment:
#      - PUID=1001
#      - PGID=1001
#    volumes:
#      - /sys:/sys