version: '3.8'

#networks:
#  monitoring:
#    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    user: 1000:1000
    hostname: rpi-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#    networks:
#      - monitoring

  node-exporter:
    container_name: monitoring-node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
#    expose:
#      - 9100
    hostname: rpi-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host
#    networks:
#      - monitoring

  prometheus:
    container_name: monitoring-prometheus
    restart: unless-stopped
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    expose:
      - 9090
    hostname: rpi-prom
    extra_hosts:
#      - "host.docker.internal:host-gateway"
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
#    networks:
#      - monitoring

  blackbox_exporter:
    image: prom/blackbox-exporter:master
    container_name: monitoring-blackbox_exporter
    restart: unless-stopped
    #    extra_hosts: *pi
#    ports:
#      - "9115:9115"
    expose:
      - 9115
    volumes:
      - ./blackbox/blackbox_config.yml:/etc/blackbox_exporter/config.yml
#    networks:
#      - monitoring

#  cadvisor:
#    container_name: monitoring-cadvisor
#    image: zcube/cadvisor:latest
#    restart: unless-stopped
#    command:
#      - '--housekeeping_interval=15s'
#      - '--docker_only=true'
#      #      - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
#      #      - '--disable_metrics=network,percpu,sched,process'
#      - '--disable_metrics=accelerator,cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp,memory_numa'
#    devices:
#      - /dev/kmsg
#    expose:
#      - 8080
#    #    hostname: rpi-cadvisor
#    ipc: shareable
#    privileged: true
#    security_opt:
#      - label=disable
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro

#  rpi_cpu_stats:
#    image: thundermagic/rpi_cpu_stats:latest
#    container_name: rpi_cpu_stats
#    restart: unless-stopped
#    ports:
#      - "9669:9669"
#    environment:
#      - PUID=1001
#      - PGID=1001
#    volumes:
#      - /sys:/sys