scrape_configs:
  - job_name: 'prometheus-local'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
#      - targets: ['monitoring-prometheus:9090']

#  - job_name: 'node-exporter-local'
  - job_name: 'rpi'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.192.180:9100', 'cadvisor:8080']
#      - targets: ['node-exporter:9100']
#      - targets: ['monitoring-node-exporter:9100']

  - job_name: 'rpi-test-docker'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.17.0.1:9100', 'cadvisor:8080', 'monitoring-node-exporter:9100']

#  - job_name: 'cadvisor'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['cadvisor:8080']

#  - job_name: 'pi_cpu_stats'
#    static_configs:
#      - targets: ['rpi_cpu_stats:9669']

  - job_name: 'rpi blackbox_ping'
    metrics_path: /probe
    scrape_interval: 30s
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
#        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
        replacement: monitoring-blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
